### PR TITLE
Adding new versions

### PR DESCRIPTION
**Pull request by solarmicrobe**
Adding spunk 2.6.1 and 2.6.2
Adding kernel check

### CODE REVIEW

**Comment by hollow** [comment]
thanks for this, i was about to update splunk as well. however, I usually do not keep old versions in the repository. this also results in a much better diff, where you can see the actual changes instead of only new files.

**Comment by solarmicrobe** [comment]
I changed to the prescribed.

**Comment by hollow** [comment]
thanks!

**Comment by solarmicrobe** [comment]
I see this failed in jenkins, looks like i forgot to update the manifest :(

**Comment by hollow** [comment]
no worries, i updated it :)

**Pull request merged**
